### ISSUE TITLE
Is there any ways to contact with you in person?

### ISSUE THREAD

**Issue by RenzVEVO** [jiellll1219/OpenDoctoratePy-EX-Public#1]
Hey there, I am heavily interested in your codebase but I ran into quite a few issues (mainly 404 errors for ODPy). And personally, I found your ideas are cool but I want to ask if it's possible for us to contact together online? (Any Mail/Texting Platform/Online works) so we can work together. I'm outside of China by the way.

**Comment by jiellll1219** [comment]
If you want to contact me, you can send an email to this address: jiege0019@gmail.com.

I am only interested in creating and maintaining this repository, and my technical skills are not very good (I only know a little bit), so the update frequency is extremely unstable. If you want to maintain it together, you can directly create a PR. As long as the code is secure, I will merge the PR.

Regarding the 404 issue you encountered, I suspect it might be related to the "shop" section. Because most of the data files can be found in other ODPY repositories. You can find the relevant files in [this repository](https://github.com/jiellll1219/LocalArknight-res/tree/main/data/shop). 
When I was writing the code, I referred to the resource files from [LocalArknight](https://github.com/jiellll1219/LocalArknight). 
If you have any questions about the storage structure of the relevant files, please refer or modify the path in constants. py.

**Comment by RenzVEVO** [comment]
Thank you, I will let you know once its done.
